# arxivの学問領域の指定
subject: 'cat:cs.AI OR cat:cs.CV OR cat:cs.NE OR cat:cs.MA'

# 検索キーワード
keywords:
        kaggle: 1
        Artificial Intelligence: 1
        Machine Learning: 1

# 通知の閾値
score_threshold: 0
